name: Try to Create OCI VM
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
env:
  OCI_CLI_REGION: "ap-singapore-1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-pip-oci-cli-v1

      - name: Add OCI CLI to path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup OCI CLI and Try to Create VM
        run: |
          pip install oci-cli

          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_CLI_USER }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_CLI_TENANCY }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "region=${{ env.OCI_CLI_REGION }}" >> ~/.oci/config
          
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > /home/runner/my_ssh_key.pub

          export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True
          export SUPPRESS_LABEL_WARNING=True

          echo "===== 🔍 正在自动获取最新参数 ====="
          MY_REAL_AD=$(oci iam availability-domain list --compartment-id "${{ secrets.OCI_COMPARTMENT_ID }}" --query "data[0].name" --raw-output)
          MY_REAL_IMAGE=$(oci compute image list --compartment-id "${{ secrets.OCI_COMPARTMENT_ID }}" --operating-system "Canonical Ubuntu" --shape "VM.Standard.A1.Flex" --query "data[0].id" --raw-output)

          echo "===== 🚀 开始发起开机，甲骨文回执将直接在下方输出 ====="
          
          # 直接运行，不通过变量中转，让甲骨文的日志直接喷在大屏幕上！
          oci compute instance launch \
            --compartment-id "${{ secrets.OCI_COMPARTMENT_ID }}" \
            --availability-domain "$MY_REAL_AD" \
            --shape "VM.Standard.A1.Flex" \
            --shape-config '{"ocpus":1,"memoryInGBs":6}' \
            --subnet-id "${{ secrets.OCI_SUBNET_ID }}" \
            --image-id "$MY_REAL_IMAGE" \
            --ssh-authorized-keys-file "/home/runner/my_ssh_key.pub" \
            --assign-public-ip true \
            --display-name "coolify-vm" \
            --boot-volume-size-in-gbs 50
